name: CI (Nightly)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
jobs:
  ci_check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Remove pinned version
        run: rm -f moonbit-version

      - name: Setup Moonup
        uses: chawyehsu/setup-moonup@v1
        with:
          moonbit-version: nightly

      - name: Check Version
        run: moon version --all

      - name: Run Tests
        run: moon test --target all -v
